Crustaly/audemywebsite

.gitignore
index.html
src/components/Header/Header.vue
src/pages/GameZone/GameZone.vue
src/pages/GameZone/GameZoneList/GameZoneList.vue
src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
tailwind.config.js

Updated GameZone Files and Hamburger menu to header in the mobile version.

Mobile version - GameZone

---

src/pages/Impact/ImpactInAction/Carousel.vue
src/pages/Impact/ImpactInAction/ImpactInAction.vue

Fixed images source
Issued HotFix

Fixed naming

---

src/pages/GameZone/GameZoneList/MultiplicationMadness.vue

Removing the media player in the multiplication madness game and reverting it back to the previous version.

Reverting the MultiplicationMadness game page

---

src/pages/AboutUs/CallToAction/CallToAction.vue
src/pages/AboutUs/Volunteers/Volunteers.vue
src/pages/AboutUs/Volunteers/VonlunteerStaff/VonlunteerStaff.vue
src/pages/AboutUs/WeAreCommitted/WeAreCommitted.vue
src/pages/AboutUs/WeAreCommitted/WeAreCommittedCard.vue

Added Mobile Compatibility to About Us Page

About Us - Mobile Compatibility 

---

src/pages/Impact/Accolades/Accolades.vue
src/pages/Impact/Accolades/AccoladesCard.vue
src/pages/Impact/CollaboratingSchools/Affiliates.vue
src/pages/Impact/CollaboratingSchools/CollaboratingSchools.vue
src/pages/Impact/CollaboratingSchools/Map.vue
src/pages/Impact/ImpactInAction/Carousel.vue
src/pages/Impact/ImpactInAction/ImpactInAction.vue
src/pages/Impact/OurReach/OurReach.vue
src/pages/Impact/PressList/PressList.vue
src/pages/Impact/PressList/PressListCard.vue

Updated the Impact Page for mobile support

Impact - Mobile support

---

src/components/Header/Header.vue

Issued fix for hamburger menu for all Pages

Hamburger menu fix

---

src/pages/OurProjects/Events/HaveYouHeard/HaveYouHeard.vue
src/pages/OurProjects/Hero/Hero.vue
src/pages/OurProjects/ResearchTech/ResearchTech.vue

Fixed, Our Projects page to display the content correctly

Bugfix - Our Projects

---

src/pages/SignUp/SignUp.js
src/pages/SignUp/SignUp.vue

Updated fields to match database naming convention.
Changed date string inputs to date input type.
Utilized Vue best practices for handling requests.
TODO:
Make sure API link is not hardcoded in the future.
Write a more readable POST request.
Notify user when passwords do not match.

Signup update

---

src/pages/LogIn/LogIn.vue

Added a simple fetch request and got Auth key on successful login.

Added fetch req for signin

---

src/pages/GameZone/GameZoneList/AdditionGame.vue

- Added a Play button to Addition game

Updated Addition Game

---

src/pages/LogIn/LogIn.vue

- Login / OAuth, unofficially completed
- OAuth and sessions completely working
Added school form 
- Front End fixes are left

Updated Login

---

src/pages/GameZone/GameZoneList/AdditionGame.vue

This PR updates the AdditionGame.vue game
Changes:
- Fixed Play button styling and padding
- Updated content container styling
- Fixed navigation behavior to use `window.history.back()` instead of explicit URL navigation
These changes ensure a consistent developer experience across our game components and a standardized UI for end users.

Fixed addition game play button

---

public/assets/questionsDb/partOfSpeechDB.json
src/Utilities/speechRecognition.js
src/pages/GameZone/GameZoneList/ColorGame.vue
src/pages/GameZone/GameZoneList/DefinitionDetective.vue
src/pages/GameZone/GameZoneList/OddOneOut.vue
src/pages/GameZone/GameZoneList/PartOfSpeech.vue
src/pages/GameZone/GameZoneList/PolarPairing.vue
src/pages/GameZone/GameZoneList/SpellingBee.vue
src/pages/GameZone/GameZoneList/SyllableSorting.vue
src/pages/GameZone/GameZoneList/Vocab.vue

- **Incorrect Answer Checking**: Updated the logic to check whether the user’s response (string) is contained within the list of correct answers.
- **Lowercase Comparison**: Added a step to convert user responses to lowercase before comparison
- **JSON Data Update**: In "Part of Speech", the word "blue" can be both a noun and an adjective. Updated the JSON data to include "noun" as an acceptable answer.

Fix answer checks, normalize input, update JSON

---

src/Utilities/speechRecognition.js
src/pages/GameZone/GameZoneList/AdditionGame.vue
src/pages/GameZone/GameZoneList/CarCounting.vue
src/pages/GameZone/GameZoneList/ColorGame.vue
src/pages/GameZone/GameZoneList/DefinitionDetective.vue
src/pages/GameZone/GameZoneList/DivisionDuel.vue
src/pages/GameZone/GameZoneList/FruitFrenzy.vue
src/pages/GameZone/GameZoneList/MonkeyMadness.vue
src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
src/pages/GameZone/GameZoneList/OddOneOut.vue
src/pages/GameZone/GameZoneList/PartOfSpeech.vue
src/pages/GameZone/GameZoneList/PolarPairing.vue
src/pages/GameZone/GameZoneList/ShapeShark.vue
src/pages/GameZone/GameZoneList/SpellingBee.vue
src/pages/GameZone/GameZoneList/SubtractionGame.vue
src/pages/GameZone/GameZoneList/SyllableSorting.vue
src/pages/GameZone/GameZoneList/Vocab.vue

Several games in the application were experiencing delays and inconsistent behavior with speech recognition functionality:
1. The speech recognition utility was not implementing continuous listening effectively
2. Sub-optimal ordering of operations when stopping the recording, causing additional perceived delays
The games recently underwent a UI overhaul, transitioning from keyboard controls (Spacebar for answers, R for question repetition) to button-based interactions. This architectural change required a complete rethinking of the speech recognition system. The original implementation was keyboard-event driven, with recognition.continuous = false and no support for interim results. We addressed this by rewriting the speech recognition utility to support continuous mode, adding proper …

Fix: Speech Recognition Responsiveness and Continuous Mode Implementation

---

.github/bug_report.yml
.github/config.yml
.github/enhancement_request.yml
.github/feature_request.yml

**Problem:**
We currently lack standardized issue templates, which can lead to inconsistent bug reports and feature/enhancement requests. This makes it harder to triage and track work on our GitHub Kanban board.
**Solution:**
This PR introduces structured, YAML-based GitHub issue templates for:
- Bug Reports
- Feature Requests
- Enhancement Requests
It also includes a config.yml to disable blank issues, ensuring contributors use these templates when opening new issues.
**Files Added:**
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/enhancement_request.yml
- .github/ISSUE_TEMPLATE/config.yml
**Dependencies / Config Changes:**
None. No runtime changes—templates are used directly by GitHub UI once merged into main.
**Checklist** …

Enhancement: Add GitHub Issue Templates for Bug, Feature, and Enhancement

---

src/pages/SignUp/SignUp.vue

This PR addresses password validation feature for the Signup page that provides immediate visual feedback to users when their password and confirmation password fields don't match.
Changes: 
- Added reactive validation for password and confirm password fields
- Implemented a color-coded alert box that displays appropriate feedback messages
- Created validation logic that triggers on input, blur events, and form submission

Signup user alert

---

public/assets/questionsDb/multiplication.json
src/Utilities/playAudio.js
src/pages/GameZone/GameZone.vue
src/pages/GameZone/GameZoneList/AdditionGame.vue
src/pages/GameZone/GameZoneList/CarCounting.vue
src/pages/GameZone/GameZoneList/ColorGame.vue
src/pages/GameZone/GameZoneList/DefinitionDetective.vue
src/pages/GameZone/GameZoneList/DivisionDuel.vue
src/pages/GameZone/GameZoneList/FruitFrenzy.vue
src/pages/GameZone/GameZoneList/MonkeyMadness.vue
src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
src/pages/GameZone/GameZoneList/OddOneOut.vue
src/pages/GameZone/GameZoneList/PartOfSpeech.vue
src/pages/GameZone/GameZoneList/PolarPairing.vue
src/pages/GameZone/GameZoneList/ShapeShark.vue
src/pages/GameZone/GameZoneList/SpellingBee.vue
src/pages/GameZone/GameZoneList/SubtractionGame.vue
src/pages/GameZone/GameZoneList/SyllableSorting.vue
src/pages/GameZone/GameZoneList/Vocab.vue

Previously, the system does not properly handle different number formats when comparing user answers to the correct answer list. For example, if the user says "two hundred thousand," the speech recognition may transcribe it as "247,500", but the system only accepts "247500" as correct. As a result, the user is marked incorrect, even though the meaning is the same.
As a temporary workaround, comma-separated number formats (e.g., "247,500") have been manually added to the list of acceptable answers for affected questions.
- `public/assets/questionsDb/multiplication.json`
For a more scalable solution, we recommend implementing a preprocessing step that normalizes number formats before comparison (e.g., removing commas or converting all answers to numeric strings).
In the long term, we could …

Fix: Added number format with comma in correct answer lists

---

src/pages/GameZone/GameZoneList/AdditionGame.vue
src/pages/GameZone/GameZoneList/CarCounting.vue
src/pages/GameZone/GameZoneList/ColorGame.vue
src/pages/GameZone/GameZoneList/DefinitionDetective.vue
src/pages/GameZone/GameZoneList/DivisionDuel.vue
src/pages/GameZone/GameZoneList/FruitFrenzy.vue
src/pages/GameZone/GameZoneList/MonkeyMadness.vue
src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
src/pages/GameZone/GameZoneList/OddOneOut.vue
src/pages/GameZone/GameZoneList/PartOfSpeech.vue
src/pages/GameZone/GameZoneList/PolarPairing.vue
src/pages/GameZone/GameZoneList/ShapeShark.vue
src/pages/GameZone/GameZoneList/SpellingBee.vue
src/pages/GameZone/GameZoneList/SubtractionGame.vue
src/pages/GameZone/GameZoneList/SyllableSorting.vue
src/pages/GameZone/GameZoneList/Vocab.vue

https://github.com/Crustaly/audemywebsite/issues/100
https://github.com/Crustaly/audemywebsite/pull/101
Added setTimeout to all games to ensure there is enough time to notify 'Incorrect' before providing the correct answer

Resolve audio overlap issue on incorrect answers

---

.prettierrc

This PR sets up Prettier to enable automatic code formatting and enforce a consistent code style guide across the project.
- https://prettier.io/docs/why-prettier

Set up Prettier

---

src/pages/ForgotPassword/ForgotPassword.vue
src/pages/LogIn/LogIn.vue
src/pages/LogIn/temp_login.vue
src/pages/ResetPassword/ResetPassword.vue
src/pages/SignUp/SignUp.js
src/pages/SignUp/SignUp.vue

This PR implements user-facing error messages for common HTTP error responses across the frontend. It ensures users receive appropriate feedback when actions fail due to issues like unauthorized access or bad requests.
The changes: 
Alert Messages for Common Errors
- 400: Invalid request alert for malformed inputs.
- 404: User not found (with console log for debugging).
- 429: Rate limiting alert.
- 500–504: Server-related errors.
- Fallback message for unexpected errors.
- Network Error Handling using a try-catch block with appropriate alert for connection issues.
These changes are to make sure users receive clear and immediate feedback when something goes wrong during their interaction with the website.

Adding appropriate messages for error handling on the frontend

---

src/pages/AboutUs/Volunteers/Staff.js

- Updated About Us
- Prettier messed it up, hence it shows everything has been changed.

re: Updated About Us

---

src/components/Game/GameControls.vue
src/components/Game/GameHeader.vue
src/components/Game/GameLayout.vue
src/components/Game/GameOver.vue
src/components/Game/PlayButton.vue
src/components/Game/StartQuestionsButton.vue
src/pages/GameZone/GameZoneList/AdditionGame.vue
src/pages/GameZone/GameZoneList/CarCounting.vue
src/pages/GameZone/GameZoneList/ColorGame.vue
src/pages/GameZone/GameZoneList/DefinitionDetective.vue
src/pages/GameZone/GameZoneList/DivisionDuel.vue
src/pages/GameZone/GameZoneList/FruitFrenzy.vue
src/pages/GameZone/GameZoneList/MonkeyMadness.vue
src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
src/pages/GameZone/GameZoneList/OddOneOut.vue
src/pages/GameZone/GameZoneList/PartOfSpeech.vue
src/pages/GameZone/GameZoneList/PolarPairing.vue
src/pages/GameZone/GameZoneList/ShapeShark.vue
src/pages/GameZone/GameZoneList/SpellingBee.vue
src/pages/GameZone/GameZoneList/SubtractionGame.vue
src/pages/GameZone/GameZoneList/SyllableSorting.vue
src/pages/GameZone/GameZoneList/Vocab.vue

https://github.com/Crustaly/audemywebsite/issues/94
Game components in the `GameZoneList` have been using the same code repeatedly. This PR addresses the issue by creating reusable `Game` components and using them across all the games.
This PR focuses solely on the UI side. The game logic refactor should be handled in a separate PR/task, as it was out of scope for this one and would have made the task too large.

Refactor Game UI Components

---

src/components/Footer/Footer.vue
src/components/ScrollUpButton/ScrollUpButton.vue
src/footer-style.css
src/style.css

- Addresses: Issue #166 
- Medium/tablet layout improved for WCAG spacing (approved by Crystal)
---
- Redesigned (mobile-first: `sm`, `md`, `lg`) to improve WCAG spacing & layout
- Refactored `<Footer />` and `<ScrollUpButton />` for maintainability
- Replaced `<box-icon>` with `<svg>` to reduce CDN use and HTTP requests
- Enhanced accessibility: reduced redundant announcements for screen readers
- Replaced plain CSS with Tailwind utilities and extracted shared styles into `footer-style.css`
---
- Inconsistent use of plain CSS & media queries  
- `<Footer />` UI didn’t align with Audemy's styling
---
<details>
<summary><i>View changes</i></summary>
- Redesigned `<Footer />` based on updated Figma (mobile-first: `sm`, `md`, `lg`)
- Replaced plain CSS with Tailwind utility classes
- …

enhancement: Footer UI Update

---

src/composables/useDeviceDetection.js
src/composables/useGameCore.js
src/config/gameConfigs.js
src/pages/GameZone/GameZoneList/AdditionGame.vue
src/pages/GameZone/GameZoneList/ColorGame.vue
src/pages/GameZone/GameZoneList/DefinitionDetective.vue
src/pages/GameZone/GameZoneList/DivisionDuel.vue
src/pages/GameZone/GameZoneList/FruitFrenzy.vue
src/pages/GameZone/GameZoneList/MonkeyMadness.vue
src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
src/pages/GameZone/GameZoneList/OddOneOut.vue
src/pages/GameZone/GameZoneList/PartOfSpeech.vue
src/pages/GameZone/GameZoneList/PolarPairing.vue
src/pages/GameZone/GameZoneList/ShapeShark.vue
src/pages/GameZone/GameZoneList/SubtractionGame.vue
src/pages/GameZone/GameZoneList/SyllableSorting.vue
src/pages/GameZone/GameZoneList/Vocab.vue

https://github.com/Crustaly/audemywebsite/issues/198
- Isolated reusable game logic into `composables` to enhance code maintainability and scalability
- Created `gameConfig` to manage common variables
- Integrated refactored logic across all games to align with the new structure
The `CarCounting` game has a significantly different structure, so it is not included in this PR. It will be addressed in future work.

Refactor game logic to improve maintainability and readability

---

src/composables/useGameCore.js
src/composables/useGameQuestions.js
src/composables/useGameUI.js

https://github.com/Crustaly/audemywebsite/issues/203
- Refactored the monolithic `useGameCore` into specialized composables

Refactor gamecore into more focused modules

---

src/Utilities/speechRecognition.js
src/components/Game/GameControls.vue
src/composables/useGameCore.js
src/composables/useGameUI.js
src/pages/GameZone/GameZoneList/AdditionGame.vue
src/pages/GameZone/GameZoneList/CarCounting.vue
src/pages/GameZone/GameZoneList/ColorGame.vue
src/pages/GameZone/GameZoneList/DefinitionDetective.vue
src/pages/GameZone/GameZoneList/DinoDetectives.vue
src/pages/GameZone/GameZoneList/DivisionDuel.vue
src/pages/GameZone/GameZoneList/EcoRangers.vue
src/pages/GameZone/GameZoneList/FruitFrenzy.vue
src/pages/GameZone/GameZoneList/GermSquad.vue
src/pages/GameZone/GameZoneList/MatterMixUp.vue
src/pages/GameZone/GameZoneList/MonkeyMadness.vue
src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
src/pages/GameZone/GameZoneList/OddOneOut.vue
src/pages/GameZone/GameZoneList/PartOfSpeech.vue
src/pages/GameZone/GameZoneList/PlantPower.vue
src/pages/GameZone/GameZoneList/PolarPairing.vue
src/pages/GameZone/GameZoneList/RobotRepair.vue
src/pages/GameZone/GameZoneList/ShapeShark.vue
src/pages/GameZone/GameZoneList/SoundExplorer.vue
src/pages/GameZone/GameZoneList/SpaceCase.vue
src/pages/GameZone/GameZoneList/SpellingBee.vue
src/pages/GameZone/GameZoneList/SubtractionGame.vue
src/pages/GameZone/GameZoneList/SyllableSorting.vue
src/pages/GameZone/GameZoneList/TinyCellTown.vue
src/pages/GameZone/GameZoneList/Vocab.vue
src/pages/GameZone/GameZoneList/WeatherWhiz.vue

- Added speech processing state management
- Enhanced user feedback
- Applied changes across all games

Prevent speech recognition interruption during processing

---

public/robots.txt
src/components/Footer/Footer.vue
src/components/Header/Header.vue
src/footer-style.css
src/form-style.css
src/pages/AboutUs/CallToAction/CallToAction.vue
src/pages/AboutUs/Volunteers/Staff.js
src/pages/AboutUs/Volunteers/Volunteers.vue
src/pages/Footer/AccessibilityStatement.vue
src/pages/Footer/PrivacyPolicy.vue
src/pages/Home/CTA/CTA.vue
src/pages/Impact/CollaboratingSchools/CollaboratingSchools.vue
src/router/index.js
src/style.css

- Updated contact emails across site (`<a>` labels and their `href`'s now use connect@audemy.org)
- Updated Footer content
- Removed fake phone number
- Added "501(c)(3)" bio, EIN, and copyright
- Removed X (Twitter) from Footer (and mobile Header)
- Added "Accessibility Statement" and "Privacy Policy" pages
- Created matching components in `src/pages/Footer/`
- Updated `robots.txt` (+ Disallowed pages) and `index.js` (+ Routing)
- Footer: Adjusted responsive grid and spacing to accommodate now-shorter email
- `Staff.js`: Removed outdated volunteer bio
- Minor fixes: 
- Updated Audemy's GitHub links (previously linked to an outdated/unofficial repo)
- Updated navbar links to use title casing for consistency
---
> [!NOTE]
> For simplicity, just the desktop previews are shown for both the …

enhancement: update responsive footer, policy pages, and contact emails

---

src/components/AccountPages/CheckmarkIcon.vue
src/components/AccountPages/PasswordChecklist.vue
src/composables/usePasswordCriteria.js
src/composables/usePasswordFeedback.js
src/form-style.css
src/pages/SignUp/SignUp.vue

- Implements dynamic password strength checklist and validation from [Issue #162](https://github.com/Crustaly/audemywebsite/issues/162)  
- **Scope:** Sign Up form only
---
- Sign Up form lacked password strength and PII (name/email) validation  
- Allowed $\color{Red}{weak, \ guessable \ passwords}$ risking compromised accounts  
---
- Live checklist with real-time validation:  
- **Required:** 8+ characters & no personal info  
- **Recommended (2+):** uppercase, lowercase, number, special character  
- Submission blocked if passwords mismatch or password is weak
<details>
<summary><i>1a. Password Criteria</i></summary>
- Computed flags: `isWeakPassword`, `hasEnoughChars`, `hasUppercase`, etc.  
- PII checks for names (first/middle/last) and email handle 
- Checks triggered on `password` …

feat: add password checklist & strength validation for sign up

---

src/composables/useCarCounting.js
src/composables/useGameNavigation.js
src/pages/GameZone/GameZoneList/CarCounting.vue

- Integrate reusable gamecore logics into CarCounting
- Added car counting specific logics into useCarCounting to align with other file structures

Refactor CarCounting to use composables

---

src/pages/Home/Testimonials/Testimonials.vue
src/pages/Impact/CollaboratingSchools/Affiliates.vue
src/pages/Impact/CollaboratingSchools/Map.vue
src/pages/Impact/OurReach/OurReach.vue
src/pages/OurProjects/ProjectsInAction/ProjectsInAction.vue

This PR applies **Prettier formatting** consistently across the entire codebase.
No functional or logic changes have been made—only code formatting adjustments based on the `.prettierrc` configuration.
---
- Ran Prettier using the command:
```bash
npx prettier --write .
- Reformatted all supported files: JavaScript, Vue, HTML, CSS, JSON, etc.
- Adjusted whitespace, indentation, and line breaks to conform to project standards.
---
Consistent code formatting helps:
- Improve readability and maintainability
- Reduce unnecessary diffs in future PRs
- Standardize team contributions
- Simplify code reviews
- Align with automated tools and CI processes
---
- **No business logic or content was altered**
- Recommend merging this PR quickly to minimize future merge conflicts
- Other contributors …
```

Chore: Prettier fix

---

src/pages/GameZone/GameZone.vue
src/pages/GameZone/GameZoneFilters/GameDropdownOptions.vue
src/pages/GameZone/GameZoneFilters/GameMenuButton.vue

- Refactors `GameZone.vue` to improve code reusability/maintainability and reduce complexity
- Improves DRY logic in all `GameZone.vue` methods
- Replaces hardcoded, WET UI elements with dynamically generated game menu/dropdown components
---
- [Issue #212](https://github.com/Crustaly/audemywebsite/issues/212): Refactor GameZone using reusable components & DRY logic
---
- **Repetitive Logic**: `GameZone.vue` contained long & repetitive `if-else` blocks for page switching logic + UI rendering
- **Hardcoded UI**: Game menu buttons & dropdowns were rendered with long, WET, hardcoded templates
- **Redundancy**: Approach to mapping game info = scattered, duplicated info
---
- Added new, reusable `<GameMenuButton />` and `<GameDropdownOptions />` components in `GameZoneFilters/`
- Updated …

refactor: add reusable Game Zone button components & DRY up logic
